### ISSUE TITLE
Trouble running this locally

### ISSUE THREAD

**Issue by trustmeimadoctor** [jzohdi/svmVisualizer#1]
Hi!

This is a cool project, but it would be very helpful if you could include a [requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) file so that others could run your code locally.

Thanks!
Navid

**Comment by jzohdi** [comment]
Hi, Navid! I have added a full requirements text file to help others with dependencies, thanks for opening this issue!
